apiVersion: v1
appVersion: 1.0.1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: hello-world-java
version: 1.0.1
